### ISSUE TITLE
Can't get promotional offers to work. 

### ISSUE THREAD

**Issue by PetrKubes97** [adaptyteam/AdaptySDK-Flutter#102]
Hi, I'm struggling to make Apple's promotional offers work. I've followed the tutorial and double checked everything, but no success. 

1. I've created promotional offer in appstore connect.
2. I've added private key to both App Store promotional offers and In-app purchases in Adapty settings.
3. I've created a product with correct App Store Product ID and App Store Offer Id.
4. I've created a paywall and selected the offer.
5. I've reset all purchases and eligibility for App Store sandbox account
6. Completely reinstalled the App

I'm still getting `subscriptionDetails.promotionalOfferId == null` for the paywall. 

Any idea how should I go about debugging this? Thanks in advance. 

Also note that I'm using Adapty 2.7.1, because 2.9.0 is not compatible with paywall builder.

**Comment by x401om** [comment]
Hi, @PetrKubes97! The thing is that Apple's promotional offers are intended for old or existing subscribers, meaning you will not be able to get a promo offer using a clean sandbox account. There are two ways you can go, depending on your goal: you can create an introductory offer using App Store Connect, and it will be automatically available to all new users, or you can test a promo offer with a user who has a purchase history.

You can read about introductory offers [here](https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/subscriptions_and_offers/implementing_introductory_offers_in_your_app) and about promo offers [there](https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/subscriptions_and_offers/setting_up_promotional_offers).

**Comment by PetrKubes97** [comment]
Thanks! It's a little confusing on Apple's side.
