### ISSUE TITLE
Setting user attributes unclear documentation

### ISSUE THREAD

**Issue by PetrKubes97** [adaptyteam/AdaptySDK-Flutter#103]
Hi, 

I'm currently connecting Amplitude to Adapty. When user logs in, I get the user id. Then, I set the Amplitude userId and update Adapty profile.

```
final builder = AdaptyProfileParametersBuilder()
      ..setAmplitudeUserId(await amplitude.getUserId());
    try {
      Adapty().updateProfile(builder.build());}...
```

From the documentation at https://docs.adapty.io/docs/setting-user-attributes, it is not clear that the previous attributes that I've set on initialization (such as device id) won't be reset. Is that the case? If so, would be nice to mention it in docs.

**Comment by x401om** [comment]
Hi, @PetrKubes97! I apologize if our documentation was unclear. We've added an additional note to clarify. Essentially, when you call `updateProfile`, all previously set attributes will remain unchanged. Please note that if you wish to delete a custom attribute, you can use the `.withRemoved(customAttributeForKey:)` method in the `AdaptyProfileParametersBuilder`.

**Comment by PetrKubes97** [comment]
Thanks 👍
