### ISSUE TITLE
packages are old,   meta: ^1.12.0

### ISSUE THREAD

**Issue by sgehrman** [adaptyteam/AdaptySDK-Flutter#105]
keep your packages updated

**Comment by x401om** [comment]
Hey there! 

The dependency is indeed set to `meta: ^1.3.0`. Just a quick heads up: [this syntax](https://dart.dev/tools/pub/dependencies#caret-syntax) allows users to install any version equal to or above 1.3.0, including 1.12.0. The flexibility of the caret (^) symbol means users with older versions can still run the SDK, but those who choose to update will benefit from the latest features and improvements. 

Let me know if you have any questions or concerns! Thanks for your attention to this matter.
