### ISSUE TITLE
makePurchase didn't return anything always generating purchase sheet again and again

### ISSUE THREAD

**Issue by akahamzidollar** [adaptyteam/AdaptySDK-Flutter#107]
I'm trying to call makPurchase function but it always generating sheet 
Here is Code:

```dart
Future<AdaptyProfile?> callMakePurchase(AdaptyPaywallProduct product) async {
    try {
      final result = await adapty.makePurchase(product: product);
      print(result);
      Get.find<AuthController>().refreshUser();
      return result;
    } on AdaptyError catch (adaptyError) {
      onAdaptyErrorOccurred?.call(adaptyError);
    } catch (e) {
      onUnknownErrorOccurred?.call(e);
    }
    return null;
  }
``` 

Screenshot:
<img src="https://github.com/adaptyteam/AdaptySDK-Flutter/assets/124251846/1f1c43fe-d12e-4943-8f96-5953d0124278" width="256"> <img src="https://github.com/adaptyteam/AdaptySDK-Flutter/assets/124251846/13f544b5-e428-4985-b98c-9bcd97e47443| width=100" width="256">

**Comment by x401om** [comment]
Hi, @akahamzidollar! The Adapty SDK does not currently support purchases made with the iOS Simulator. Please monitor [this](https://github.com/adaptyteam/AdaptySDK-iOS/issues/82) issue for further details.

**Comment by akahamzidollar** [comment]
@x401om! Thank you for reply. This issue was produced on simulator and real device as well. But when i set StoreKit 2 Configuration  on Adapty dashboard this issue was solved.
