### ISSUE TITLE
What about apple privacy manifest ?

### ISSUE THREAD

**Issue by fullflash** [adaptyteam/AdaptySDK-Flutter#108]
Hi. we are considering adapty as an alternative to revenuecat.
But this packages has no privacy manifest file.
Are there any plans ?

**Comment by x401om** [comment]
Hi @fullflash! Adapty iOS SDK is already supporting this manifest since [2.10.2](https://github.com/adaptyteam/AdaptySDK-iOS/releases/tag/2.10.2) so it should be available on current Adapty Flutter SDK. Do you have any issues with this manifest?
