### ISSUE TITLE
Any progress with upgrading Gradle and Android compileSDK

### ISSUE THREAD

**Issue by Schefferbird** [adaptyteam/AdaptySDK-Flutter#109]
Are you close to commit and push changes to pub dev any time soon?

**Comment by vladd-g** [comment]
Hey @Schefferbird 

Our support has contacted you, could you please tell us if the issue was fully resolved? Thank you!

**Comment by vladd-g** [comment]
Hey @Schefferbird

Our support contacted you earlier. Could you please tell us if the issue was fully resolved? Thank you!
