### ISSUE TITLE
Product model crash (iOS)

### ISSUE THREAD

**Issue by Another1dd** [adaptyteam/AdaptySDK-Flutter#11]
Crashed: com.apple.main-thread
0  libswiftFoundation.dylib       0x103542f04 static Locale._unconditionallyBridgeFromObjectiveC(_:) + 4421201668
1  Adapty                         0x1008e5198 $s6Adapty12ProductModelC02skB0So9SKProductCSgvW + 480
2  Adapty                         0x1008d1c38 $s6Adapty10IAPManagerC12paymentQueue_21shouldAddStorePayment3forSbSo09SKPaymentD0C_So0J0CSo9SKProductCtFTf4dnnn_n + 604
3  Adapty                         0x1008cf80c $s6Adapty10IAPManagerC12paymentQueue_21shouldAddStorePayment3forSbSo09SKPaymentD0C_So0J0CSo9SKProductCtFTo + 96
4  StoreKit                       0x196628d6c __NotifyObserverAboutPendingAppStorePayments + 160
5  CoreFoundation                 0x182584680 CFArrayApplyFunction + 80
6  StoreKit                       0x196628c60 -[SKPaymentQueue _notifyObserversAboutPurchaseIntentsForProducts:] + 352
7  StoreKit                       0x196627638 -[SKPaymentQueue _sendAppStorePendingPaymentsRequestForMessage:] + 192
8  StoreKit                       0x196628378 __44-[SKPaymentQueue _handleMessage:connection:]_block_invoke + 168
9  libdispatch.dylib              0x181fb0aa0 _dispatch_call_block_and_release + 24
10 libdispatch.dylib              0x181fb0a60 _dispatch_client_callout + 16
11 libdispatch.dylib              0x181fbd65c _dispatch_main_queue_callback_4CF$VARIANT$mp + 1012
12 CoreFoundation                 0x182667070 CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE + 12
13 CoreFoundation                 0x182664bc8 __CFRunLoopRun + 2272
14 CoreFoundation                 0x182584da8 CFRunLoopRunSpecific + 552
15 GraphicsServices               0x184569020 GSEventRunModal + 100
16 UIKit                          0x18c5a1758 UIApplicationMain + 236
17 libswiftUIKit.dylib            0x10379d468 UIApplicationMain(_:_:_:_:) + 3912
18 Runner                         0x1005199d0 main + 4370700752 (NotificationsAppDelegate.swift:4370700752)
19 libdyld.dylib                  0x182015fc0 start + 4

**Comment by AKyashkin** [comment]
Happens only on iOS 11.x
We'll get back to this one after additional details on user's locales.

**Comment by x401om** [comment]
Hey, @Another1dd! 
We have released version 2 of our SDK. If something like this still reproduces, please, reopen the problem.
