### ISSUE TITLE
Google has requested that the Google Play Billing Library be updated to at least 6.0.1 by August 31, but we are limited by Adapty's SDK

### ISSUE THREAD

**Issue by Tangxiaochuanle** [adaptyteam/AdaptySDK-Flutter#113]
Google has requested that the Google Play Billing Library be updated to at least 6.0.1 by August 31, but we are limited by Adapty's SDK and we need the corresponding version of flutter adaptysdk

**Comment by vladd-g** [comment]
@Tangxiaochuanle which sdk version do you use? We support PBL 6 from v2.6.x

**Comment by Tangxiaochuanle** [comment]
Okay, that's taken care of. Thank you

**Comment by shrijanRegmi** [comment]
I'm using v2.7.0 but Google Play still throws this warning that I need to update Google Play Billing Library.

Can you confirm that Play Billing Library is indeed v6? Because in the [change log](https://pub.dev/packages/adapty_flutter/changelog#260) it says v5 has been implemented.

**Comment by vladd-g** [comment]
@shrijanRegmi yes, we specified _v5+_ because there were drastic changes particularly in v5, but the actual dependency was v6
