### ISSUE TITLE
Adapty not activating successfully

### ISSUE THREAD

**Issue by PetrKubes97** [adaptyteam/AdaptySDK-Flutter#116]
Hi, 
after updating to flutter 3.24.1 and adapty_flutter 2.10.2, I've started getting the following issue.

Adapty().activate() runs successfully, but all subsequent calls fails:

I/flutter ( 5697): [AdaptyFlutter v2.10.2] - VERBOSE: --> Adapty.identify()
I/flutter ( 5697): [AdaptyFlutter v2.10.2] - VERBOSE: <-- Adapty.identify() Adapty Error (code: 20, message: Adapty was not initialized, detail: null)

Paywalls can't be retrieved either. 

I haven't tried it with other projects yet, but it works in debug mode and does not in release mode (apk). I haven't tried app bundles yet. 

Any ideas?

**Comment by vladd-g** [comment]
Hi @PetrKubes97 

> but it works in debug mode and does not in release mode

usually it's related to obfuscation issues

could you please try adding the following to your proguard config file?
`-keep class com.adapty.** { *; }`

**Comment by PetrKubes97** [comment]
Hi, unfortunately does not seem to work.
```
buildTypes {
        release {
            signingConfig signingConfigs.release
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
        }
    }
```
proguard-rules.pro:
```
-keep class com.adapty.** { *; }
```

**Comment by PetrKubes97** [comment]
I'm thinking, is it necessary to have a certain version of gradle? I'm still using the Flutter default 7.x + declarative build.gradle https://docs.flutter.dev/release/breaking-changes/flutter-gradle-plugin-apply.

**Comment by vladd-g** [comment]
could you please try upgrading? as [here](https://github.com/adaptyteam/AdaptySDK-Flutter/commit/a4aa048af0dea816db96c727f7d4aad9b92351ab)

**Comment by PetrKubes97** [comment]
I've had troubles with other libraries not being compatible with that.

**Comment by vladd-g** [comment]
what are those errors?

and, as a workaround, you can try reverting those changes locally, in _~/.pub-cache/hosted/pub.dev/adapty_flutter-2.10.2/android/build.gradle_

**Comment by PetrKubes97** [comment]
Not sure. I remember some problems with R8. I'll test it more in the evening. Either way, I think the SDK should work with the default flutter settings, but it might just be my project.

**Comment by HarmonyV** [comment]
> Hi, after updating to flutter 3.24.1 and adapty_flutter 2.10.2, I've started getting the following issue.
> 
> Adapty().activate() runs successfully, but all subsequent calls fails:
> 
> I/flutter ( 5697): [AdaptyFlutter v2.10.2] - VERBOSE: --> Adapty.identify() I/flutter ( 5697): [AdaptyFlutter v2.10.2] - VERBOSE: <-- Adapty.identify() Adapty Error (code: 20, message: Adapty was not initialized, detail: null)
> 
> Paywalls can't be retrieved either.
> 
> I haven't tried it with other projects yet, but it works in debug mode and does not in release mode (apk). I haven't tried app bundles yet.
> 
> Any ideas?

I'm having a similar issue, my stack does lock a little different thought. I've tried the above suggestions but they didn't solve the issue. Works fine in debug but fails in release.

```
I/flutter (  847): [AdaptyFlutter v2.10.2] - VERBOSE: --> Adapty.set_log_level()
I/flutter (  847): [AdaptyFlutter v2.10.2] - VERBOSE: <-- Adapty.set_log_level()
I/flutter (  847): [AdaptyFlutter v2.10.2] - VERBOSE: --> Adapty.get_profile()
I/flutter (  847): [AdaptyFlutter v2.10.2] - VERBOSE: <-- Adapty.get_profile() Adapty Error (code: 20, message: Adapty was not initialized, detail: null)
E/flutter (  847): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: (code: 20, message: Adapty was not initialized, detail: null)
E/flutter (  847): #0      Adapty._invokeMethodHandlingErrors (package:adapty_flutter/src/adapty.dart:301)
E/flutter (  847): <asynchronous suspension>
E/flutter (  847): #1      Adapty.getProfile (package:adapty_flutter/src/adapty.dart:59)
E/flutter (  847): <asynchronous suspension>
E/flutter (  847): #2      AdaptyServices.checkSubscriptionStatus (package:bmi_calculator/services/monetization_services/adapty_services.dart:133)
E/flutter (  847): <asynchronous suspension>
E/flutter (  847): #3      main (package:bmi_calculator/main.dart:27)
E/flutter (  847): <asynchronous suspension>
E/flutter (  847): 
```

**Comment by vladd-g** [comment]
Could you please try _v2.10.3_?

**Comment by HarmonyV** [comment]
Update:

so apparently in my case, the issue occurred because I updated my Gradle version to 8.3 (also tried 8.4). Which I find extremely odd. After reverting back to gradle 7.6.3 adapty works as intended.

**Comment by vladd-g** [comment]
@LoadJulz replied [here](https://github.com/adaptyteam/AdaptySDK-Flutter/issues/119#issuecomment-2395358953)

**Comment by tomquas** [comment]
FWIW i could solve the problem on android - at least in debug mode - with the help of support:

pass the api key to activation like this: **Adapty().activate(apiKey: <key>);**

no need to roll back to gradle 7.x; my setup: flutter 3.24.4, gradle 8.3, java 17

**Comment by vladd-g** [comment]
you can also try disabling `fullMode` as shown in the snippet [here](https://developer.android.com/build/shrink-code#full-mode)
