### ISSUE TITLE
Gradle Issue after Upgrading

### ISSUE THREAD

**Issue by LoadJulz** [adaptyteam/AdaptySDK-Flutter#119]
I wanted to upgrade Gradle to 8.x, but I get the following error building my release build:
<img width="1013" alt="image" src="https://github.com/user-attachments/assets/f81dc7e4-32be-422c-95b1-0a7153189558">

I also have followed the Gradle versions like in the Adapty repository mentioned [here](https://github.com/adaptyteam/AdaptySDK-Flutter/commit/a4aa048af0dea816db96c727f7d4aad9b92351ab).

I also have added `-keep class com.adapty.** { *; }` to the proguard-rules.pro 

All those things don't change something. I can debug my Android app but I am unable to build a release build.

My current Adapty version is 2.10.3

**Comment by vladd-g** [comment]
Hi @LoadJulz 

Could you please try [this](https://github.com/adaptyteam/AdaptySDK-React-Native/issues/117#issuecomment-2053623435) solution?

**Comment by LoadJulz** [comment]
Hi, yes this helped!!! Thank you!

**Comment by HarmonyV** [comment]
@LoadJulz to which gradle version are you upgrading? I tried 8.3 and 8.4 and I got an error saying adapty is not initialized.
only 7.1.3 works for me, which is sad seeing as I'll have to transition to i higher version at some point.

**Comment by LoadJulz** [comment]
@HarmonyV I have upgrade my Gradle to 8.3.0. I only tested it on debug mode so far and had no issues with Adapty getting initalized. Did you upgrade Adapty to the latest version? I am happy to help you!

**Comment by LoadJulz** [comment]
What is the issue saying exactly for you? Could you post your stacktrace?

**Comment by HarmonyV** [comment]
@LoadJulz 
it's the same output as here, but using 2.10.3 instead: https://github.com/adaptyteam/AdaptySDK-Flutter/issues/116#issuecomment-2373903436
