### ISSUE TITLE
Example run error

### ISSUE THREAD

**Issue by andim27** [adaptyteam/AdaptySDK-Flutter#123]
E/Adapty_v3.1.0( 6046): ERROR: Play Market request failed: Google Play In-app Billing API version is less than 3
E/Adapty_v3.1.0( 6046): ERROR: UI v3.1.0 error: -1414329673 loadProducts error: Play Market request failed: Google Play In-app Billing API version is less than 3
![Screenshot_1732204995](https://github.com/user-attachments/assets/8f59b27c-f1f1-4e9a-9f2c-7250a73d43c3)

**Comment by vladd-g** [comment]
Hi @andim27 

Please make sure the device has Play Market and you are logged in there

**Comment by andim27** [comment]
Next error:
Resolving dependencies... (1.2s)
Because adapty_ui_flutter 2.1.3 depends on adapty_flutter ^2.10.2 
Please if you update adapty_flutter update adapty_ui_flutter too, thanks

**Comment by vladd-g** [comment]
@andim27 you don't need the `adapty_ui_flutter` dependency anymore since v3
