### ISSUE TITLE
Error: You need to be activate Adapty once

### ISSUE THREAD

**Issue by hasimyerlikaya** [adaptyteam/AdaptySDK-Flutter#124]
Even though I check the status with `Adapty().isActivated()` before activation, `Adapty().activate(...)` returns error 3005.

The `Adapty().isActivated()` method returns false.

It seems like it’s not working correctly.

```
adapty_flutter: ^3.2.2
Flutter: 3.24.5 (stable)
Dart: 3.5.4 (stable)
iOS: 18.1.1
```

Error:
` (code: 3005, message: You need to be activate Adapty once, detail: {"detail":"AdaptyError.activateOnceError([3.2.0]: Adapty\/Adapty+Activate.swift#65)","adapty_code":3005,"message":"You need to be activate Adapty once"})`

```
late final initJob = JobResultAsync<bool>(
    () async {
      if (isActivated) {
        return true;
      }

      final nativeCheck = await Adapty().isActivated();
      if (nativeCheck) {
        return true;
      }

      await Adapty().activate(
        configuration: AdaptyConfiguration(
          apiKey: AppArgs.adaptyKey,
        ),
      );

      return true;
    },
    onError: (result) {
      print(result.error);
    },
  );
```

**Comment by atoka93** [comment]
It also happens for when running on iOS: once I added the API key to `Info.plist` file, it started happening only on hot restarts even though I ran `flutter clean` after.

**Comment by ferhatAksoy** [comment]
Having same issue

**Comment by obenkucuk** [comment]
After updating to version 3+, I started experiencing the same issue.

**Comment by obenkucuk** [comment]
> @x401om , @vladd-g we're experiencing the same issue on Android. When we first install, it is working normally. But when you perform hot restart, adapty prints this error.
> 
> E/Adapty_v3.1.0(29444): ERROR: Adapty was already activated. If you want to provide new customerUserId, please call 'identify' function instead.
> 
> We tried to check with isActivated but no luck. I think in native side, it continue to keep last activation even if hot restart happens.



> @x401om , @vladd-g we're experiencing the same issue on Android. When we first install, it is working normally. But when you perform hot restart, adapty prints this error.
> 
> E/Adapty_v3.1.0(29444): ERROR: Adapty was already activated. If you want to provide new customerUserId, please call 'identify' function instead.
> 
> We tried to check with isActivated but no luck. I think in native side, it continue to keep last activation even if hot restart happens.

I have checked that isActivated method and it calls this function on native side. Still, it returns incorrect answer.

**Comment by x401om** [comment]
Hi everyone! Thank you for your patience. We’ve just released [version 3.2.3](https://github.com/adaptyteam/AdaptySDK-Flutter/releases/tag/3.2.3), which ensures that isActivated correctly returns the native SDK activation status.

Please make sure to use `Adapty().setupAfterHotRestart()` and `AdaptyUI.setupAfterHotRestart(observer:)` after a hot restart so the plugin can properly receive messages from the native side.

I assume you’ll implement the activation flow something like this:

```dart
import 'package:adapty_flutter/adapty_flutter.dart';
import 'package:flutter/foundation.dart';

Future<void> activateAdaptyIfNeeded() async {
    try {
        var isActivated = false;

        // Please consider not using this in production to avoid any unwanted effects
        if (kDebugMode) {
            isActivated = await Adapty().isActivated();
        } else {
            isActivated = false;
        }

        if (!isActivated) {
            await Adapty().activate(configuration: <YOUR_CONFIGURATION_OBJECT>);
            await AdaptyUI().activate(observer: <YOUR_OBSERVER_OBJECT>);
        } else {
            Adapty().setupAfterHotRestart();
            AdaptyUI().setupAfterHotRestart(observer: this);
        }
    } catch (e) {
        // handle the error
    }
}
```

**Comment by sajithlascade** [comment]
The method 'setupAfterHotRestart' isn't defined for the type 'AdaptyUI'.

**Comment by melihcelik-hubx** [comment]
// Please consider not using this in production to avoid any unwanted effects
still unstable for production or are there any recommended uses?
@x401om
