### ISSUE TITLE
Null-safety support

### ISSUE THREAD

**Issue by AlexandrFarkas** [adaptyteam/AdaptySDK-Flutter#13]
Is this package still maintained? Will null-safety be integrated?

**Comment by AKyashkin** [comment]
@AlexandrFarkas Hey,
Yes, we will introduce this migration in the beginning of the next week.
I'll let you know in this thread.

**Comment by AKyashkin** [comment]
@AlexandrFarkas it's available in 1.0.0-nullsafety.0 pre-release.
https://github.com/adaptyteam/AdaptySDK-Flutter/tree/1.0.0-nullsafety.0
