### ISSUE TITLE
3.x.x sdk issue

### ISSUE THREAD

**Issue by aligurelli** [adaptyteam/AdaptySDK-Flutter#132]
in app purchases and subscriptions working well on 2.x.x sdk on both **testflight** and **sandbox** mode. but when i upgrade flutter sdk to 3.x.x i am getting "purchase is not allowed for this device" error for both on sandbox and testlight. i already sent a e-mail to support@adapty.com and received a message including "our ios team says that its related with apple". but definetly its not since its working as expected with 2.x.x

also, i implemented [superwall](www.superwall.com) sdk to make sure the problem is not on my side. and  there was no issue with superwall too, everything worked as expected. so please fix this issue asap 🙏 i can share my p8 file,issuer id, key id and an other necessary informations with you via email to make you replicate this issue on your side. also i can add you as developer to my account to replicate this issue if its required. please reach out to me if you need this informations: **gurellidevs@gmail.com**

so briefly:

-  IAP and subscriptions works as expected with 2.x.x adapty flutter sdk version
-  IAP and subscriptions works as expected with superwall's latest sdk version - www.superwall.com
-  IAP and subscriptions **does not work with 3.x.x adapty flutter sdk version** - getting **"purchase is not allowed for this device" error** for both on sandbox and testflight

**Comment by x401om** [comment]
Hi @aligurelli! I understand that you currently have an active inquiry with our support team. We are awaiting the verbose logs. I will keep the issue open in the meantime.

**Comment by aligurelli** [comment]
> Hi @aligurelli! I understand that you currently have an active inquiry with our support team. We are awaiting the verbose logs. I will keep the issue open in the meantime.

i already shared with support team. can you check please

**Comment by aligurelli** [comment]
> Hi @aligurelli! I understand that you currently have an active inquiry with our support team. We are awaiting the verbose logs. I will keep the issue open in the meantime.

sorry just saw their new mail. they wanted me to update 3.2.3 and then share logs again. will be updating you :)

**Comment by aligurelli** [comment]
@x401om hello 👋

the issue is still there. i updated 3.2.3 sdk version and still having the issue. also shared log on google docs:

https://docs.google.com/document/d/1QeGh9uS2ggCmiu4Dk5zf0PAlYVYiieYnadMqJ4zuST8/edit?usp=sharing


ps: even though i updated 3.2.3 version the logs still say adapty sdk version 3.2.1 for some reason.

**Comment by aligurelli** [comment]
> @aligurelli Please avoid sharing logs directly here, as they may contain sensitive information. I have removed the link from your comment. I will review the logs and respond to you through the support team. Thank you!

hi 👋 is there any news? i need to send the update asap since apple will have a christmas break :/

**Comment by aligurelli** [comment]
> @aligurelli Please avoid sharing logs directly here, as they may contain sensitive information. I have removed the link from your comment. I will review the logs and respond to you through the support team. Thank you!

hi. i just recieved a message from support team. the developer said: 'As far as I can see from the logs, they are using the iOS simulator without any active Sandbox account or even StoreKit configuration files. While we don’t fully support StoreKit configuration files, it is possible to fetch products if such a file is used. Please suggest they use a real device with a Sandbox account created via App Store Connect and try again."


as i mentioned on the issue description: i already tried both sandbox mode with a real device created by ApStore Connect. i already tried from testflight build from 5 different iphone. the result is same. also:

IAP and subscriptions works as expected with 2.x.x adapty flutter sdk version
IAP and subscriptions works as expected with superwall's latest sdk version - [www.superwall.com](http://www.superwall.com/)
IAP and subscriptions does not work with 3.x.x adapty flutter sdk version - getting "purchase is not allowed for this device" error for both on sandbox and testflight

**Comment by aligurelli** [comment]
> Hi @aligurelli, you’ve shared the logs from the iOS Simulator. Please run the application on a real device and send us its verbose logs so we can investigate the error.

surely. doing it right now

**Comment by aligurelli** [comment]
> > Hi @aligurelli, you’ve shared the logs from the iOS Simulator. Please run the application on a real device and send us its verbose logs so we can investigate the error.
> 
> surely. doing it right now

@x401om just sent it to support team :) again, the sandbox user is registered on appstore connect. its working with 2.x.x sdk, as well as superwall 😊 thank you for your helps!

please feel free to reach out me directy by gurellidevs@gmail.com if you need any information such as adding you into appstore connect team as developer.

**Comment by x401om** [comment]
@aligurelli We noticed you are activating Adapty with `observerMode: true`. It is not possible to use `makePurchase` method in Observer Mode, please consider using the full mode.
