### ISSUE TITLE
Cannot build iOS app since updating to 3.2.x

### ISSUE THREAD

**Issue by biklas7** [adaptyteam/AdaptySDK-Flutter#133]
After updating my adapty dependency and making the necessary changes, when I try to build my app on iOS I get errors. See attached logs.
[logs.txt](https://github.com/user-attachments/files/18061369/logs.txt)

**Comment by x401om** [comment]
Hi @biklas7! Please kindly share your flutter doctor output and Cocoapods version you are using

**Comment by biklas7** [comment]
Sure!

Cocoapods version: 1.16.2

Flutter doctor:
```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.24.5, on macOS 15.1.1 24B91 darwin-arm64, locale en-PT)
[✓] Android toolchain - develop for Android devices (Android SDK version 35.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.2)
[✓] VS Code (version 1.95.3)
[✓] Connected device (4 available)
[✓] Network resources

• No issues found!
```

**Comment by x401om** [comment]
@biklas7 I believe there might be an issue with your plugin integration. Could you please ensure that you have properly updated the plugin and run `pod install` or `pod update Adapty`? I also recommend cleaning the Derived Data and the build folder.

**Comment by biklas7** [comment]
@x401om I just tried doing what you've suggested and still it does not build 😢

**Comment by biklas7** [comment]
I suspected this issue happens because you guys updated to Swift 6 or something like that and are now also using Swift Package Manager, but I also tried updating flutter to main channel and enable the Swift Package Manager and it also does not work.

The only way it works for us is to revert to version 2.x unfortunately.

**Comment by PBomermustekiin** [comment]
update your flutter
flutter clean,
flutter pub get,
cd ios
pod install
pod update Adapty

**Comment by biklas7** [comment]
> flutter upgrade (update your flutter) flutter clean, flutter pub get, cd ios pod install pod update Adapty

@PBomermustekiin obviously that was the first thing I tried. It didn't work.



> @biklas7 Updating our SDK to Swift 6 does not require you to update the Swift version of your project. In the file you attached in the original message, I noticed numerous errors, which I suspect may be related to incorrect dependency resolution.
> 
> By the way, we support CocoaPods as the primary distribution channel for our cross-platform SDKs, at least until Flutter fully transitions to SPM. However, I’m not entirely sure if it currently works with SPM.
> 
> Could you please try running our example app included with version 3.2.3? Are there any issues with it?

@x401om sorry didn't have time yet to try the example, will try as soon as possible and get back to you.

**Comment by biklas7** [comment]
@x401om It does build with the example app 🤔 so weird, do you have hints on how I can try solving this issue?

**Comment by x401om** [comment]
@biklas7 Please take some screenshots of your Xcode showing the errors and email them to agoncharov_at_adapty.io. I will try to help.

**Comment by berkansevimli** [comment]
Same issue:

Launching lib/main.dart on iPhone 15 Pro Max in debug mode...
Xcode build done.                                           47,5s
Failed to build iOS app
Swift Compiler Error (Xcode): Call to main actor-isolated initializer 'init(_:additionalPadding:drawDecoratorBackground:)' in a synchronous nonisolated context
/Volumes/Disk/env/myApp/ios/Pods/AdaptyUI/AdaptyUI/Rendering/Elements/AdaptyUIElementView.swift:97:12

Swift Compiler Error (Xcode): Call to main actor-isolated initializer 'init(_:additionalPadding:drawDecoratorBackground:)' in a synchronous nonisolated context
/Volumes/Disk/env/myApp/ios/Pods/AdaptyUI/AdaptyUI/Rendering/Templates/AdaptyUIFlatContainerView.swift:29:16

Swift Compiler Error (Xcode): Call to main actor-isolated initializer 'init(_:additionalPadding:drawDecoratorBackground:)' in a synchronous nonisolated context
/Volumes/Disk/env/myApp/ios/Pods/AdaptyUI/AdaptyUI/Rendering/Templates/AdaptyUIFlatContainerView.swift:33:12

Swift Compiler Error (Xcode): Cannot find 'onGeometryChange' in scope
/Volumes/Disk/env/myApp/ios/Pods/AdaptyUI/AdaptyUI/Rendering/Modifiers/AdaptyUIGeometrySizeObserver.swift:45:12

Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code

Could not build the application for the simulator.
Error launching application on iPhone 15 Pro Max.


Exited (1).

**Comment by x401om** [comment]
@berkansevimli which Xcode and Swift version are you using for this project?

**Comment by berkansevimli** [comment]
@x401om Flutter doctor:

`[✓] Flutter (Channel stable, 3.22.0, on macOS 14.1 23B74 darwin-arm64, locale tr-TR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 15.0.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.1)
[✓] VS Code (version 1.90.2)
[✓] Connected device (5 available)
[✓] Network resources
`

`
pod --version
1.16.2
`

**Comment by x401om** [comment]
@berkansevimli please update to [3.2.4](https://github.com/adaptyteam/AdaptySDK-Flutter/releases/tag/3.2.4)
