### ISSUE TITLE
Error adaptyUI after update adapty_flutter 3.2.2 -> 3.2.4

### ISSUE THREAD

**Issue by Silverviql** [adaptyteam/AdaptySDK-Flutter#136]
After update package return this error

/ios/Pods/AdaptyUI/AdaptyUI/Rendering/Elements/AdaptyUIElementView.swift:98:13 Call to main actor-isolated initializer 'init(_:additionalPadding:drawDecoratorBackground:)' in a synchronous nonisolated context

/ios/Pods/AdaptyUI/AdaptyUI/Rendering/Templates/AdaptyUIFlatContainerView.swift:30:17 Call to main actor-isolated initializer 'init(_:additionalPadding:drawDecoratorBackground:)' in a synchronous nonisolated context
/ios/Pods/AdaptyUI/AdaptyUI/Rendering/Templates/AdaptyUIFlatContainerView.swift:34:13 Call to main actor-isolated initializer 'init(_:additionalPadding:drawDecoratorBackground:)' in a synchronous nonisolated context

  - Adapty (3.2.2)
  - adapty_flutter (3.2.4):
    - Adapty (= 3.2.2)
    - AdaptyPlugin (= 3.2.2)
    - AdaptyUI (= 3.2.2)
    - Flutter
  - AdaptyPlugin (3.2.2):
    - Adapty (= 3.2.2)
    - AdaptyUI (= 3.2.2)
  - AdaptyUI (3.2.2):
    - Adapty (= 3.2.2)
    
   

pod --version
1.16.2
 ruby -v                
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin23]

**Comment by x401om** [comment]
@Silverviql do you have the same error while building our Example app?

**Comment by Silverviql** [comment]
@x401om 
yes, only I had to edit the Podfile for the pod install to happen

me change  platform :ios, '15.0' and target 'Runner' do
  use_frameworks!  # if needed for dynamic frameworks
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

end


this is what android studio returns

> Swift Compiler Error (Xcode): Call to main actor-isolated initializer 'init(_:additionalPadding:drawDecoratorBackground:)' in a synchronous nonisolated context
> /Users/programming/localhost/package_example/AdaptySDK-Flutter/example/ios/Pods/AdaptyUI/AdaptyUI/Rendering/Elements/AdaptyUIElementView.swift:97:12
> 
> Swift Compiler Error (Xcode): Call to main actor-isolated initializer 'init(_:additionalPadding:drawDecoratorBackground:)' in a synchronous nonisolated context
> /Users/programming/localhost/package_example/AdaptySDK-Flutter/example/ios/Pods/AdaptyUI/AdaptyUI/Rendering/Templates/AdaptyUIFlatContainerView.swift:29:16
> 
> Swift Compiler Error (Xcode): Call to main actor-isolated initializer 'init(_:additionalPadding:drawDecoratorBackground:)' in a synchronous nonisolated context
> /Users/programming/localhost/package_example/AdaptySDK-Flutter/example/ios/Pods/AdaptyUI/AdaptyUI/Rendering/Templates/AdaptyUIFlatContainerView.swift:33:12
> 
> Uncategorized (Xcode): Command SwiftCompile failed with a nonzero exit code
> 
> Could not build the application for the simulator.
> Error launching application on iPhone 15 Pro.

**Comment by Silverviql** [comment]
@x401om I ran your example through xcode, this is what it returns

<img width="1145" alt="image" src="https://github.com/user-attachments/assets/a111e4ec-5fa3-4638-980f-36d483e1fd2b" />

**Comment by x401om** [comment]
Hi @Silverviql, please try [3.2.5](https://github.com/adaptyteam/AdaptySDK-Flutter/releases/tag/3.2.5)
