### ISSUE TITLE
Android get paywalls bug

### ISSUE THREAD

**Issue by Another1dd** [adaptyteam/AdaptySDK-Flutter#14]
E/flutter ( 8702): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: type 'Null' is not a subtype of type 'String'
E/flutter ( 8702): #0      new AdaptyProduct.fromMap (package:adapty_flutter/models/adapty_product.dart:98:24)
E/flutter ( 8702): #1      new AdaptyPaywall.fromMap.<anonymous closure> (package:adapty_flutter/models/adapty_paywall.dart:43:138)
E/flutter ( 8702): #2      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
E/flutter ( 8702): #3      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
E/flutter ( 8702): #4      new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter ( 8702): #5      new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter ( 8702): #6      new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter ( 8702): #7      ListIterable.toList (dart:_internal/iterable.dart:211:44)
E/flutter ( 8702): #8      new AdaptyPaywall.fromMap (package:adapty_flutter/models/adapty_paywall.dart:43:153)
E/flutter ( 8702): #9      new GetPaywallsResult.fromMap.<anonymous closure> (package:adapty_flutter/results/get_paywalls_result.dart:10:105)
E/flutter ( 8702): #10     MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
E/flutter ( 8702): #11     ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
E/flutter ( 8702): #12     new _GrowableList._ofEfficientLengthIterable (dart:core-patch/growable_array.dart:188:27)
E/flutter ( 8702): #13     new _GrowableList.of (dart:core-patch/growable_array.dart:150:28)
E/flutter ( 8702): #14     new List.of (dart:core-patch/array_patch.dart:50:28)
E/flutter ( 8702): #15     ListIterable.toList (dart:_internal/iterable.dart:211:44)
E/flutter ( 8702): #16     new GetPaywallsResult.fromMap (package:adapty_flutter/results/get_paywalls_result.dart:10:117)
E/flutter ( 8702): #17     Adapty.getPaywalls (package:adapty_flutter/adapty_flutter.dart:62:30)

**Comment by AKyashkin** [comment]
Fixed in 1.0.0-nullsafety.0 pre-release.
