### ISSUE TITLE
Google Play Console Resubscribe

### ISSUE THREAD

**Issue by AlexandrFarkas** [adaptyteam/AdaptySDK-Flutter#15]
After uploading APK with Adapty SDK, Google play console states in 'subscriptions' section: 
"Resubscribe is not currently available for your users because your app does not use Billing Library 2.0 in all active APKs."

**Comment by vladd-g** [comment]
Hi, Adapty uses Billing Library 3.0.3. Everything was ok with 'resubscribe' before?

**Comment by vladd-g** [comment]
@AlexandrFarkas
Where did you upload the apk? (I mean closed alpha/beta/etc.) Maybe Google haven't finished the review yet, and that's the reason?

**Comment by AlexandrFarkas** [comment]
@vladd-g 
Both closed testing and internal testing

**Comment by vladd-g** [comment]
@AlexandrFarkas 
Maybe that's because your production app is considered as "active" (reference to "because your app does not use Billing Library 2.0 in all active APKs") and doesn't use Billing Library 2.0+. Anyway, Adapty uses the latest version of Billing Library

**Comment by AlexandrFarkas** [comment]
@vladd-g Thanks a lot,  I will try to fix this myself. Seems, there is no problem with library itself.
