### ISSUE TITLE
localizedSubscriptionPeriod is null, but subscription period is defined.

### ISSUE THREAD

**Issue by AlexandrFarkas** [adaptyteam/AdaptySDK-Flutter#16]
adapty_flutter 1.0.0-nullsafety.0

localizedSubscriptionPeriod = null

<img width="350" alt="Screenshot 2021-05-21 at 23 56 35" src="https://user-images.githubusercontent.com/35890159/119172446-2e503f00-ba90-11eb-92e3-a9f2a25b9892.png">

I suppose, it's a bug.

**Comment by AKyashkin** [comment]
@AlexandrFarkas Hey, what's locale of your device?

**Comment by AlexandrFarkas** [comment]
@AKyashkin Android Simulator, 'en' locale. Products are defined in RU at Google Play Console.

**Comment by vladd-g** [comment]
@AlexandrFarkas Android SDK, and thus Flutter SDK on Android devices, does not have this property since Billing Library doesn't return localized interpretations for time periods
