### ISSUE TITLE
Price for products is null in release mode.

### ISSUE THREAD

**Issue by AlexandrFarkas** [adaptyteam/AdaptySDK-Flutter#17]
localizedDescirption, vendorProductId are present, but price is null.
Everything works fine in debug

Edit 1: subscriptionPeriod is also null.

**Comment by AKyashkin** [comment]
@AlexandrFarkas Hey, 
For such case it's better to reach out support via Intercom (through your personal dashboard).
Speficy platform and app name there, so we can help you with detailed insights.
