### ISSUE TITLE
Get paywalls mapping from json error

### ISSUE THREAD

**Issue by Another1dd** [adaptyteam/AdaptySDK-Flutter#2]
1. First error:
Unhandled Exception: NoSuchMethodError: The method 'map' was called on null.
Tried calling: map<AdaptyPaywall>(Closure: (dynamic) => AdaptyPaywall)
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      new GetPaywallsResult.fromJson (package:adapty_flutter/results/get_paywalls_result.dart:12:68)
#2      Adapty.getPaywalls (package:adapty_flutter/adapty_flutter.dart:68:30)
<asynchronous suspension>

2. Second error:
Unhandled Exception: FormatException: Unexpected end of input (at character 1)
#0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1404:5)
#1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:522:7)
#2      _parseJson (dart:convert-patch/convert_patch.dart:41:10)
#3      JsonDecoder.convert (dart:convert/json.dart:505:36)
#4      JsonCodec.decode (dart:convert/json.dart:156:41)
#5      new AdaptyPaywall.fromMap (package:adapty_flutter/models/adapty_paywall.dart:36:91)
#6      new GetPaywallsResult.fromJson.<anonymous closure> (package:adapty_flutter/results/get_paywalls_result.dart:12:93)
#7      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#8      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#9      new List.from (dart:core-patch/array_patch.dart:38:29)
#10     new List.of (dart:core-patch/array_patch.dart:68:17)
#11     ListIterable.toList (dart:_internal/iterable.dart:211:44)
#12     new GetPaywallsResult.fromJson (package:adapty_flutter/results/get_paywalls_result.dart:12:105)
#13     Adapty.getPaywalls (package:adapty_flutter/adapty_flutter.dart:68:30)

**Comment by kpotehin** [comment]
Fixed in https://github.com/adaptyteam/AdaptySDK-Flutter/commit/3fc36abcad852d5442336acd05018a89135938dc
