### ISSUE TITLE
Introductory Offers missed

### ISSUE THREAD

**Issue by sanekyy** [adaptyteam/AdaptySDK-Flutter#20]
Hello. Why there is no information about Introductory Offers on iOS?

I can't find anything in model about this. Is it your mistake or I don't understand something?

**Comment by AKyashkin** [comment]
@sanekyy Hey,
It's in `AdaptyProduct` model, take a look at [introductoryDiscount](https://github.com/adaptyteam/AdaptySDK-Flutter/blob/master/lib/models/adapty_product.dart#L59) property.
