### ISSUE TITLE
Add docs for fields and methods on Adapty

### ISSUE THREAD

**Issue by sanekyy** [adaptyteam/AdaptySDK-Flutter#21]
All methods without docs:( 
Fix it please.

![image](https://user-images.githubusercontent.com/18647037/123547203-87cf1c00-d768-11eb-9a16-e3ea3a0f850f.png)

**Comment by AKyashkin** [comment]
@sanekyy Hey,
We already have pretty rich documentation [here](https://doc.adapty.io/docs).
For now, we don't have any plans related to code docs so far.
