### ISSUE TITLE
adapty appsflyer integration not working

### ISSUE THREAD

**Issue by Horum-dev** [adaptyteam/AdaptySDK-Flutter#26]
Hello Adapty! we integrated a service 2 months ago and added AppsFlyer as integration. However, the event list is empty! 

Adapty package has only **updateAttribution** and we provided it like this:
`appsflyer.appOpenAttributionStream.listen((event) async {
      logInitialSource(event);
      Adapty.updateAttribution(event,
          source: AdaptyAttributionNetwork.appsflyer,
          networkUserId: await appsflyer.getAppsFlyerUID());
    });`
    
  But the list is empty, and your docs says that there should be events 
<img width="1555" alt="Снимок экрана 2021-08-19 в 10 15 05" src="https://user-images.githubusercontent.com/67152395/130024775-f387a584-1ce7-4466-abcc-c068d838a3ca.png">

here https://docs.adapty.io/docs/event-feed you show logging subscriptions to appsflyer 
![image](https://user-images.githubusercontent.com/67152395/130025191-a34b3a83-dde2-4248-b75f-cca9edcad718.png)

Help please!

**Comment by Horum-dev** [comment]
any news?

**Comment by AKyashkin** [comment]
Hey, sorry for long response.
We'll take a look and get back to you.

**Comment by AKyashkin** [comment]
@Horum-dev it's easier and faster to use Intercom for such support cases like you have.
But in general, you only need to properly collect attribution. Here is an example of how to obtain it:

```
@override
Future<bool> initialize() async {
	appsflyerSdk.onInstallConversionData((data) {
		return _applyConversionData(data);
    });

    await appsflyerSdk.initSdk(
	    registerConversionDataCallback: true,
	    registerOnAppOpenAttributionCallback: true,
	    registerOnDeepLinkingCallback: true
	);

	return Future<bool>.value(true);
}
```

**Comment by Horum-dev** [comment]
> @Horum-dev it's easier and faster to use Intercom for such support cases like you have.
> But in general, you only need to properly collect attribution. Here is an example of how to obtain it:
> 
> ```
> @override
> Future<bool> initialize() async {
>     appsflyerSdk.onInstallConversionData((data) {
>         return _applyConversionData(data);
>     });
> 
>     await appsflyerSdk.initSdk(
> 	registerConversionDataCallback: true,
> 	registerOnAppOpenAttributionCallback: true,
> 	registerOnDeepLinkingCallback: true
>     );
> 
>     return Future<bool>.value(true);
> }
> ```

doing the same thing, not working.

**Comment by AKyashkin** [comment]
Can you send a samples of attribution you receiving from AppsFlyer?
And one more time – for such cases it's better to ask support directly through website Intercom.
