### ISSUE TITLE
introductoryOfferEligibility and promotionalOfferEligibility not working in Android

### ISSUE THREAD

**Issue by otopba** [adaptyteam/AdaptySDK-Flutter#29]
In android products `introductoryOfferEligibility` and `promotionalOfferEligibility` are always false. 
Even if it is a new user. Although, if you click on the payment, the native screen will show that the discount applies. Does it look like some kind of bug or are the checks not working for android?

**Comment by vladd-g** [comment]
@otopba, `promotionalOfferEligibility` only exists on iOS, so it's always false on Android.

Is the issue about `introductoryOfferEligibility` still relevant with the newest version of the SDK?

**Comment by otopba** [comment]
@vladd-g I haven't updated to the latest version yet. When I update, I'll post the result here
