### ISSUE TITLE
Android update attribution "Reply already submitted" crash

### ISSUE THREAD

**Issue by Another1dd** [adaptyteam/AdaptySDK-Flutter#3]
E/AndroidRuntime(20367): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(20367): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:139)
E/AndroidRuntime(20367): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:238)
E/AndroidRuntime(20367): 	at com.adapty.flutter.AdaptyFlutterPlugin.emptyResultOrError(AdaptyFlutterPlugin.kt:331)
E/AndroidRuntime(20367): 	at com.adapty.flutter.AdaptyFlutterPlugin.access$emptyResultOrError(AdaptyFlutterPlugin.kt:33)
E/AndroidRuntime(20367): 	at com.adapty.flutter.AdaptyFlutterPlugin$handleUpdateAttribution$1$2.invoke(AdaptyFlutterPlugin.kt:238)
E/AndroidRuntime(20367): 	at com.adapty.flutter.AdaptyFlutterPlugin$handleUpdateAttribution$1$2.invoke(AdaptyFlutterPlugin.kt:33)
E/AndroidRuntime(20367): 	at com.adapty.Adapty$Companion$updateAttribution$1$1.success(Adapty.kt:640)
E/AndroidRuntime(20367): 	at com.adapty.api.ApiClient$success$myRunnable$1.run(ApiClient.kt:320)
E/AndroidRuntime(20367): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(20367): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(20367): 	at android.os.Looper.loop(Looper.java:223)
E/AndroidRuntime(20367): 	at android.app.ActivityThread.main(ActivityThread.java:7656)
E/AndroidRuntime(20367): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20367): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
E/AndroidRuntime(20367): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

**Comment by vladd-g** [comment]
fixed in https://github.com/adaptyteam/AdaptySDK-Flutter/commit/a8588e6d071a44e5af8f3165b763311036e7af04
