### ISSUE TITLE
PushHandler not working with target 31

### ISSUE THREAD

**Issue by otopba** [adaptyteam/AdaptySDK-Flutter#32]
E/MethodChannel#flutter.adapty.com/adapty(19824): java.lang.IllegalArgumentException: dev.optimist.worddaily: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
E/MethodChannel#flutter.adapty.com/adapty(19824): Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at com.adapty.push.AdaptyPushHandler.createPendingIntent(AdaptyPushHandler.kt:73)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at com.adapty.push.AdaptyPushHandler.buildNotification(AdaptyPushHandler.kt:61)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at com.adapty.push.AdaptyPushHandler.handleNotification(AdaptyPushHandler.kt:40)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at com.adapty.flutter.AdaptyFlutterPlugin.handlePushReceived(AdaptyFlutterPlugin.kt:355)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at com.adapty.flutter.AdaptyFlutterPlugin.onMethodCall(AdaptyFlutterPlugin.kt:87)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:233)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:84)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:869)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at android.os.MessageQueue.next(MessageQueue.java:335)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at android.os.Looper.loopOnce(Looper.java:161)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at android.os.Looper.loop(Looper.java:288)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at android.app.ActivityThread.main(ActivityThread.java:7838)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/MethodChannel#flutter.adapty.com/adapty(19824): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)

**Comment by vladd-g** [comment]
@otopba thank you for the report, we'll fix

**Comment by vladd-g** [comment]
@otopba fixed in release 1.0.8

**Comment by otopba** [comment]
🎉
