### ISSUE TITLE
Error building app on Android - HELP

### ISSUE THREAD

**Issue by officialFlutterDeveloper** [adaptyteam/AdaptySDK-Flutter#33]
it works and builds fine on IOS

but on android I get

Type inference failed: Not enough information to infer parameter R in inline fun <T, R> T.let(block: (T) -> R): R
Please specify it explicitly.

/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/adapty_flutter-0.3.6/android/src/main/kotlin/com/adapty/flutter/AdaptyFlutterPlugin.kt: (162, 101): Unresolved reference: logShowPaywall

* What went wrong:
Execution failed for task ':adapty_flutter:compileDebugKotlin'.
> Compilation error. See log for more details

im using  adapty_flutter: ^0.3.4

**Comment by otopba** [comment]
@officialFlutterDeveloper Try the latest version of the library 1.0.7. It will work

**Comment by officialFlutterDeveloper** [comment]
> @officialFlutterDeveloper Try the latest version of the library 1.0.7. It will work

I thought upgrading the version would help but no luck here's what I get 

e: /Users/Craig/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/adapty_flutter-1.0.7/android/src/main/kotlin/com/adapty/flutter/AdaptyFlutterPlugin.kt: (134, 52): Expecting an argument
e: /Users/Craig/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/adapty_flutter-1.0.7/android/src/main/kotlin/com/adapty/flutter/AdaptyFlutterPlugin.kt: (245, 42): Expecting an argument
e: /Users/Craig/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/adapty_flutter-1.0.7/android/src/main/kotlin/com/adapty/flutter/AdaptyFlutterPlugin.kt: (213, 63): Unresolved reference: from
e: /Users/Craig/Developer/flutter/.pub-cache/hosted/pub.dartlang.org/adapty_flutter-1.0.7/android/src/main/kotlin/com/adapty/flutter/AdaptyFlutterPlugin.kt: (495, 60): Unresolved reference: from

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adapty_flutter:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by officialFlutterDeveloper** [comment]
also did these steps 

https://docs.adapty.io/docs/android-installation

But no luck

**Comment by vladd-g** [comment]
@officialFlutterDeveloper hi, I suppose you have Kotlin 1.3.x version in your build.gradle file, please change it to 1.4.32 and the problem will be gone

**Comment by officialFlutterDeveloper** [comment]
that was indeed the solution thank you
