### ISSUE TITLE
getPromo method only for iOS

### ISSUE THREAD

**Issue by otopba** [adaptyteam/AdaptySDK-Flutter#34]
Can you please tell me why the `getPromo` method can only be used on ios?

![image](https://user-images.githubusercontent.com/4225279/144029826-d0f724b9-aaa9-4993-a5db-fda94bdfbfa6.png)

If you look at the android part of the library's implementation, you can see that there is call processing.

Please make the method work on both platforms

![image](https://user-images.githubusercontent.com/4225279/144029902-e51458fe-4aff-4c10-a81f-366a3b194193.png)

**Comment by AKyashkin** [comment]
Fixed in https://github.com/adaptyteam/AdaptySDK-Flutter/releases/tag/1.0.9
