### ISSUE TITLE
deferredPurchaseProduct or defferedPurchaseProduct

### ISSUE THREAD

**Issue by otopba** [adaptyteam/AdaptySDK-Flutter#35]
A typo in the word deffered -> deferred

![image](https://user-images.githubusercontent.com/4225279/144442040-bcc1f893-25f7-4231-9da3-82b5889570b4.png)

**Comment by AKyashkin** [comment]
Fixed in https://github.com/adaptyteam/AdaptySDK-Flutter/releases/tag/1.0.9
