### ISSUE TITLE
Make Adapty a singleton

### ISSUE THREAD

**Issue by layerzzzio** [adaptyteam/AdaptySDK-Flutter#42]
Adapty is currently only like a namespace for several functions and has several static functions.
As the functions are static it makes it hard to mock Adapty to write tests.

Would be better to adopt something like:
https://github.com/FirebaseExtended/flutterfire/blob/master/packages/cloud_firestore/cloud_firestore/lib/src/firestore.dart

This would allow to mock and verify calls to Adapty, like:

verify(mockAdapty.whateverFunction();
verifyNoMoreInteractions(mockAdapty.whateverFunction);

**Comment by x401om** [comment]
Hi, @layerzzzio! Thanks for the idea, it seems pretty reasonable and interesting. At the moment, the public interface of the Flutter SDK is completely the same on iOS and Android, but there will probably be significant changes on both in the near future. We will try to design the interface in a way that satisfies your request and solves the issue of automatic testing :)
