### ISSUE TITLE
How to get profile and custom attribute data

### ISSUE THREAD

**Issue by mehul9spl** [adaptyteam/AdaptySDK-Flutter#44]
How can i get profile data from adapty?
How can i get custom attribute data from adapty set by "AdaptyProfileParameterBuilder"?

**Comment by x401om** [comment]
Hey, @mehul9spl! What kind of data do you need to get? 
You can read about PurchaserInfo [here](https://docs.adapty.io/docs/flutter-subscription-status) and about setting custom user attributes [here](https://docs.adapty.io/docs/setting-user-attributes). Also feel free to contact our technical support, using Intercom.
