### ISSUE TITLE
release app bundle doesn't display products

### ISSUE THREAD

**Issue by mehul9spl** [adaptyteam/AdaptySDK-Flutter#45]
I am working on adapty subscription
when i test my app on release apk then it display all product from google play store
but when i make release app bundle then it not display any product from google play store

**Comment by VladimirCourse** [comment]
Having the same problem. Here some logs

```
I/flutter (10797): #0      Adapty._invokeMethodHandlingErrors (package:adapty_flutter/adapty_flutter.dart:240)
I/flutter (10797): <asynchronous suspension>
I/flutter (10797): #1      Adapty.getPaywalls (package:adapty_flutter/adapty_flutter.dart:64)
I/flutter (10797): <asynchronous suspension>
....
I/flutter (10797): AdaptyError (code null) 
```

**Comment by vladd-g** [comment]
@mehul9spl @VladimirCourse 
I suppose it can be an obfuscation-related problem, could you please add the following line to proguard config if you don't have it yet?
```-keep class com.adapty.** { *; }```

**Comment by demirdev** [comment]
Same error, 
In the Adapty dashboard my android app settings, not inform to me: 'SDK is installed and working'
