### ISSUE TITLE
Make purchase mapping error ( iOS)

### ISSUE THREAD

**Issue by Another1dd** [adaptyteam/AdaptySDK-Flutter#5]
[VERBOSE-2:ui_dart_state.cc(177)] Unhandled Exception: FormatException: Trying to read yyyy from 2020-12-15T18:53:38+0300 at position 0
#0      _DateFormatField.throwFormatException (package:intl/src/intl/date_format_field.dart:87:5)
#1      _DateFormatPatternField.parseField (package:intl/src/intl/date_format_field.dart:337:7)
#2      _DateFormatPatternField.parse (package:intl/src/intl/date_format_field.dart:250:5)
#3      DateFormat._parse (package:intl/src/intl/date_format.dart:374:13)
#4      DateFormat.parse (package:intl/src/intl/date_format.dart:303:7)
#5      MapExtension.dateTimeOrNull (package:adapty_flutter/helpers/extensions.dart:7:46)
#6      new AdaptyAccessLevelInfo.fromJson (package:adapty_flutter/models/adapty_access_level_info.dart:100:28)
#7      new AdaptyPurchaserInfo.fromJson.<anonymous closure> (package:adapty_flutter/models/adapty_purchaser_info.dart:30:156)
#8      MapMixin.map (dart:collection/maps.dart:170:28)
#9      new AdaptyPurchaserInfo.fromJson (package:adapty_flutter/models/adapty_purchaser_info.dart:30:100)
#10     new MakePurchaseResult.fromJson (package:adapty_flutter/results/make_purchase_result.dart:15:85)
#11     Adapty.makePurchase (package:adapty_flutter/adapty_flutter.dart:86:31)

**Comment by x401om** [comment]
Hey, @Another1dd! 
We have released version 2 of our SDK. If something like this still reproduces, please, reopen the issue.
