### ISSUE TITLE
Update Native Adapty Dependencies

### ISSUE THREAD

**Issue by ibrahimdevs** [adaptyteam/AdaptySDK-Flutter#54]
Hi,

This plugin uses native iOS and Android SDK, but very old ones. Could you update native dependencies to latest ones?

For example;
Adapty Flutter 1.0.2 plugin is using Native Adapty iOS 1.16.10. Actually there is 1.17.7 is available for Native iOS. We are following nearly 10 versions behind.

Thanks,

**Comment by x401om** [comment]
Hi, @ibrahimdevs! We are planning to release a new version of Adapty Flutter SDK next week.

**Comment by x401om** [comment]
Hi, @ibrahimdevs, I have released the new version, check it out!
