### ISSUE TITLE
Why does the user have to sign in with his apple id when first installing an app using Adapty?

### ISSUE THREAD

**Issue by Tobi696** [adaptyteam/AdaptySDK-Flutter#55]
It kind of affects the UX of the app I am developing. When you open my app, the first screen is a sign in screen with email+password, apple id, facebook or google account.
Now, after adding the adapty SDK and calling `Adapty.activate()`, a popup opens where the user has to sign in with his apple id.
I hope you understand that it affects the UX negatively. How can I avoid that?

**Comment by iwitaly** [comment]
You can check from the source code that Adapty SDK does not affect your UI/UX in any possible way.

**Comment by Tobi696** [comment]
@iwitaly it doesn't affect flutter ui, but it triggers a native iOS dialogue where the user has to log in with his apple id.

**Comment by x401om** [comment]
Hi, @Tobi696! Indeed, you may get this dialog if you have not currently authorized your Apple Id account. In the case of sandbox testing this happens quite often, but in the production environment everything will be fine and the user will not get an authorization prompt unless you manually call the `restorePurchases` method.

**Comment by Tobi696** [comment]
Alright, thank you guys!
