### ISSUE TITLE
AdaptyError (code null) Product type is null

### ISSUE THREAD

**Issue by ysahin20** [adaptyteam/AdaptySDK-Flutter#60]
Hello, we are building an app and installed the Adapty SDK in order to have good and easy iap.
We did connected both AppStore and Google Play and also added ios sdk and android sdk.
Then we created products and paywalls. However, when we tried to get the product prices on android, we couldn't get the prices.
All of them are "0.0". 

Also when we tried to make a purchase we get an error which is "AdaptyError (code null) Product type is null".

I have no idea about solving these probles, we would be very grateful if you could help us.

**Comment by vladd-g** [comment]
@ysahin20 Hi, I suppose the problem is about the access to products in Play Market as a tester. Could you please check out our [guide](https://docs.adapty.io/docs/testing-purchases-android)?

**Comment by ysahin20** [comment]
@vladd-g As you said, the problem was about the access of the testers. Now i have the problem that says "the irem you requested is not available for purchase" but i will keep rewieving the guide about it and thank you for your response.
