### ISSUE TITLE
Android is not running

### ISSUE THREAD

**Issue by onuracikgozdusyeri** [adaptyteam/AdaptySDK-Flutter#63]
App is crashing after the splash screen. When i remove meta-data in androidmanifest.xml project is building. Do i need to add code block to java or kotlin native code block?

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/98304729/199755317-d38492c3-5da9-4f1b-b3e9-5cf3532d9342.png">

**Comment by onuracikgozdusyeri** [comment]
@vladd-g i did not add v5 manually but it is come from in_app_purchases package. can it be problem?

**Comment by vladd-g** [comment]
@onuracikgozdusyeri yes, it can. Is in_app_purchases package being used in your project after adding Adapty, or you can remove it?

As for manually adding, you can try the following:
```
implementation('com.android.billingclient:billing') {
        version {
            strictly '4.0.0'
        }
    }
```

But please check if nothing fails because of in_app_purchases package (if you don't remove it) since the compatibility may be broken

**Comment by onuracikgozdusyeri** [comment]
@vladd-g thanks that is worked but i am getting crash when i try reload func in_app_purchases package :( 
when will adapty be upgraded to v5 .
Is there any chance of using v5 or v4 depending on the package?

**Comment by vladd-g** [comment]
@onuracikgozdusyeri Do you need in_app_purchases package to be included? Since you can make purchases with Adapty

**Comment by onuracikgozdusyeri** [comment]
@vladd-g yeah we need :)

**Comment by vladd-g** [comment]
@onuracikgozdusyeri 

> i am getting crash when i try reload func in_app_purchases package

Sorry, I didn't get, could you please specify what kind of crash are you getting and when?

Btw, is it an option to downgrade in_app_purchases down to the latest with v4 in its dependencies?

**Comment by onuracikgozdusyeri** [comment]
@vladd-g we removed iap package thanks
