### ISSUE TITLE
Android showVisualPaywall blank screen problem

### ISSUE THREAD

**Issue by onuracikgozdusyeri** [adaptyteam/AdaptySDK-Flutter#64]
how i can show paywall screen. i' m getting blank white screen when i try this func on android

![image](https://user-images.githubusercontent.com/98304729/200436443-15d678bd-05eb-433a-8ede-0040ae0c1345.png)

**Comment by x401om** [comment]
Hey, @onuracikgozdusyeri! 
I apologize for the long response. This functionality was available in beta mode, and we do not support it at the moment. Perhaps in the future we will come back to this feature, but in the latest version of our SDK these features have been eliminated.
