### ISSUE TITLE
Android restorePurchases return empty. 

### ISSUE THREAD

**Issue by onuracikgozdusyeri** [adaptyteam/AdaptySDK-Flutter#65]
I have a subscription on playstore side. but when i try restorePurchases return 
`
'purchaserInfo: customerUserId: null, accessLevels: {}, subscriptions: {}, nonSubscriptions: {}, receipt: nullgoogleValidationResult: null'`

**Comment by x401om** [comment]
@onuracikgozdusyeri are you still facing this issue? Could you please try our new SDK version? 
Read more about it [here](https://github.com/adaptyteam/AdaptySDK-Flutter/releases/tag/2.2.0).

If yes, please, send us a verbose log from Adapty.

**Comment by x401om** [comment]
I will close this issue, since there has been no answer for a long time. If the problem occurs again, feel free to reopen it.
