### ISSUE TITLE
AdaptyError (code null) Play Market request failed: Google Play In-app Billing API version is less than 3

### ISSUE THREAD

**Issue by furkancetintass** [adaptyteam/AdaptySDK-Flutter#78]
I see this error in Sentry issues while **getPaywalls** running 
adapty_flutter: ^2.2.4

```
adapty_flutter.dart in Adapty._invokeMethodHandlingErrors at line 241 within adapty_flutter
Called from: <asynchronous suspension>
adapty_flutter.dart in Adapty.getPaywalls at line 64 within adapty_flutter
Called from: <asynchronous suspension>
adapty_service.dart in AdaptyService.getProducts at line 59 within uppy
Called from: <asynchronous suspension>
premium_viewmodel.dart in PremiumViewModel.getProductsFromAdapty at line 779 within uppy
Called from: <asynchronous suspension>
premium_viewmodel.dart in PremiumViewModel.createAppSubscriptionOptions at line 215 within uppy
```

**Comment by vladd-g** [comment]
hi @furkancetintass 

I suppose it was either an emulator or a device without Google Play

**Comment by furkancetintass** [comment]
hi @vladd-g 

Among the devices where this problem occurs is the iPhone 11

**Comment by x401om** [comment]
@furkancetintass that is impossible to get Google Play related errors from iOS. Are you sure that Sentry is aggregating error data correctly?

**Comment by x401om** [comment]
As I said above, there is no way to get an error related to Google Play on an iOS device. I think there are some inaccuracies here in how the information was collected (it happens that analytics systems mix stack traces incorrectly). If possible, please send us a verbose log for the sessions with errors.

**Comment by UlasKasim-dusyeri** [comment]
iOS devices produce error as `AdaptyError (code 0) Bilinmeyen bir hata oluştu`
Android devices produce error as `AdaptyError (code null) Play Market request failed: An internal error occurred.`

**Comment by x401om** [comment]
I'll close the issue since there is no response. Feel free to reopen if you will be able to provide more information or verbose logs from the SDK.
