### ISSUE TITLE
Update Kotlin & Gradle Version

### ISSUE THREAD

**Issue by ibrahimdevs** [adaptyteam/AdaptySDK-Flutter#79]
Hi,

Current kotlin version is too old and it keeps from us to update recent gradle versions/kotlin versions.

Please update andoid/build.gradle file;
- ext.kotlin_version = '1.4.20' to at least '1.5.20' - If you can more it is better. You can do it '1.6.10'
- classpath 'com.android.tools.build:gradle:4.1.0' to at least 'com.android.tools.build:gradle:7.3.1'

Thanks,

**Comment by vladd-g** [comment]
hi @ibrahimdevs 

I suppose you can upgrade Kotlin version on the app level, you may have a file similar to this (https://github.com/adaptyteam/AdaptySDK-Flutter/blob/master/example/android/build.gradle#L2), it's where you can upgrade both Kotlin and Gradle

Or have you encountered problems updating them on the app side?

**Comment by ibrahimdevs** [comment]
hi @vladd-g ,
Thanks for very quick response. I upgrade the gradle version in my project to "com.android.tools.build:gradle:7.3.1" and "kotlin_version = '1.6.10' then when I try to run my app, there is an error;

`The Android Gradle plugin supports only Kotlin Gradle plugin version 1.5.20 and higher.
The following dependencies do not satisfy the required version:
project ':adapty_flutter' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.20`

**Comment by vladd-g** [comment]
@ibrahimdevs got it, we'll try to fix it in the next release! Thank you!

**Comment by x401om** [comment]
Hey @ibrahimdevs, we have fixed this in the latest release!
