### ISSUE TITLE
The user profile was replaced

### ISSUE THREAD

**Issue by tonbert** [adaptyteam/AdaptySDK-Flutter#80]
Hi, the following error occurs when i want to identify an user after login or token refresh.

```
Adapty().activate();
await Adapty().setLogLevel(AdaptyLogLevel.verbose);
...
await Adapty().identify(action.account.id);
```
The identify() Method never resolves and freezes the app. Sometimes i see this error output:

```
Performing hot reload...
Syncing files to device iPhone SE (3rd generation)...
Reloaded 1 of 1367 libraries in 430ms (compile: 27 ms, reload: 149 ms, reassemble: 238 ms).
flutter: [AdaptyFlutter v2.2.4] - VERBOSE: --> Adapty.identify()
flutter: [AdaptyFlutter v2.2.4] - VERBOSE: <-- Adapty.identify() Adapty Error (code: 3006, message: The user profile was replaced, detail: AdaptyError.profileWasChanged([2.2.2]: Adapty/Adapty+ChangeState.swift#150))
```

**Comment by x401om** [comment]
Hi, @tonbert! 

This error can occur when you run a parallel identify process and another one that depends on the user's profile. If during the identify process the profile has changed, this error will be returned for the rest of the requests, in which case you need to retry the request.

**Comment by tonbert** [comment]
ok, it works, thank you
