### ISSUE TITLE
AdaptyError.productPurchaseFailed (code 1006) when user actually cancelled the purchase on iOS

### ISSUE THREAD

**Issue by SebastianEngel** [adaptyteam/AdaptySDK-Flutter#83]
I was just testing a product purchase with the `makePurchase(product)` method on an iPhone. The iOS purchase action sheet opened, showing the subscription information and the "Subscribe" button. When I then close the action sheet with the 'X' button, I would expect that this would result in `AdaptyError.paymentCancelled` (error code 2). Instead I get `AdaptyError.productPurchaseFailed` (error code 1006). Because of that it's impossible to properly handle "purchase canceled" and "purchase failed" in different ways, right?

Additional info: I tested in Sandbox environment with a Sandbox user if this might make a difference.

**Comment by x401om** [comment]
Hey, @SebastianEngel! Quite interesting behaviour. Could you please send me the verbose logs from the SDK?

**Comment by x401om** [comment]
We have found an issue in the iOS SDK. Will be fixed soon.
