### ISSUE TITLE
Support macOS

### ISSUE THREAD

**Issue by Caqil** [adaptyteam/AdaptySDK-Flutter#86]
Support macOS

**Comment by x401om** [comment]
Hey, @Caqil!
We do have plans to support macOS, but we don't have a specific estimate at the moment. We appreciate your patience and understanding. Stay tuned for future updates!

P.S. If you're up for it, you have the freedom to create your own implementation and submit a pull request. We appreciate community contributions and would be more than happy to review your code and potentially integrate it into our plugin.

**Comment by x401om** [comment]
Since this issue is not related to the actual bug or problem, I am going to close it.
