### ISSUE TITLE
Error 1000 - No In-app Purchase product identifiers were found

### ISSUE THREAD

**Issue by DholaSain** [adaptyteam/AdaptySDK-Flutter#87]
In-app products are working with RevenueCat but not with Adapty. Every time I try to get the In-app purchase products, it shows the products but can't purchase them.

For the subscriptions, it is not even getting the subscription data from the Playstore console.

I am using the same methods provided in PurchaseObserver class in the Example project.

I've reviewed all the docs and setup accordingly. 

```Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.10.3, on macOS 13.4 22F66 darwin-arm64, locale en-PK)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Community Edition (version 2023.1.2)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources```

**Comment by vladd-g** [comment]
hi @DholaSain 

As for subscriptions, are there right product ids in the Adapty Console? We are about to release the new version that supports multiple base plans per product, but for now you need to add the `product id`, not the `base plan id`.

As for in-app products, is your Google account a tester and a License tester? Could you please check with [this article](https://docs.adapty.io/docs/testing-on-android) if everything's ok?

**Comment by DholaSain** [comment]
I am still unable to load the products on paywall.
I have two subscriptions with IDs:

`ID: sheentv_monthly , Base Plan: sheentv-monthly`
`ID: sheentv_yearly , Base Plan: sheentv-yearly`

I am using in Adapty dashboard as following.
1. [Adapty Dashboard Screenshot 1](https://firebasestorage.googleapis.com/v0/b/geekybugs-apps.appspot.com/o/Screenshots%2Fsheen%2FScreenshot%202023-07-31%20at%201.09.39%20PM.png?alt=media&token=9db76395-faa2-4715-8537-366f6a0d6547)

2. [Adapty Dashboard Screenshot 2](https://firebasestorage.googleapis.com/v0/b/geekybugs-apps.appspot.com/o/Screenshots%2Fsheen%2FScreenshot%202023-07-31%20at%201.09.54%20PM.png?alt=media&token=f13bded8-91b9-47f1-b628-f47ae1ac4dfb)

**Output of getPaywall()**
`(id: sheentv, name: SheenTV, abTestName: SheenTV, variationId: ed90cbc0-7001-466b-b612-511da8fdf4a5, revision: 7, locale: en, remoteConfigString: , _products: [(vendorId: sheentv_monthly, promotionalOfferEligibility: false, introductoryOfferEligibility: AdaptyEligibility.unknown, promotionalOfferId: null, _version: 1690797565883), (vendorId: sheentv_yearly, promotionalOfferEligibility: false, introductoryOfferEligibility: AdaptyEligibility.unknown, promotionalOfferId: null, _version: 1690797565883)], _version: 1683288095393)`

**Error on getPaywallProducts() with above paywall.**
_Error 1000 - No In-app Purchase product identifiers were found_

**Comment by x401om** [comment]
@DholaSain I would recommend you to send an email to [support@adapty.io](mailto:support@adapty.io). I am pretty sure the problem is not with the SDK but with the store/dashboard configuration. My colleagues will help you resolve the issue.
