### ISSUE TITLE
Breaking changes (remove fields localizedPrice, localizedSubscriptionPeriod, etc) without notice

### ISSUE THREAD

**Issue by al-tush** [adaptyteam/AdaptySDK-Flutter#91]
In version 2.6.0 some fields was removed without update version to 3.0.
This is against the rules SemVer https://semver.org/spec/v2.0.0-rc.1.html

**Comment by MJ12358** [comment]
Updated today and can confirm that the api has breaking changes without a semantic version update.

In my specific use case:
`AdaptyPaywallProduct.localizedPrice` no longer exists and there is no documentation that offers an alternative.

It seems that they have replaced this with `AdaptyPaywallProduct.price` which points to a new class called `AdaptyPrice`.

However the comments within that class suggest that `amount` and `localizedString` are for "discounts"? Is this correct and if so what do we need to use in favor of `localizedPrice`?
