### ISSUE TITLE
Free trials do not show up on 2.6.2 in Android

### ISSUE THREAD

**Issue by Arcturus5404** [adaptyteam/AdaptySDK-Flutter#94]
In version 2.4.4 free trials were found and could be shown.

in version 2.6.2 these are no longer were they are supposed to be?

`product.subscriptionDetails?.introductoryOffer`

This yields an empty list.

**Comment by kantanta** [comment]
I have a similar situation.

**Comment by LuoChengAndroid** [comment]
I have a similar situation.

**Comment by vladd-g** [comment]
Hi @Arcturus5404 

Could you please check whether you've added an offer to _the paywall_? Since a product can be purchased with various of its offers or with no offer at all, it's important to specify an offer on the specific paywall

**Comment by Arcturus5404** [comment]
it has been added to the paywall, but still nothing shows up

**Comment by vladd-g** [comment]
@Arcturus5404 Is the Google account you're testing on eligible for the trial? From version 2.4.4 to 2.6.2, we migrated the Billing Library from v4 to v6, and starting from version 5, it doesn't return offers that a user is not eligible for.

**Comment by Arcturus5404** [comment]
Thats it! Switching to another test account fixed this for me!

Thank you so much
