### ISSUE TITLE
Adapty UI builder crashing on Android

### ISSUE THREAD

**Issue by PetrKubes97** [adaptyteam/AdaptySDK-Flutter#97]
Hi, I'm trying to use the Adapty UI builder. The UI correctly displays on iOS devices, however, is crashes on Android with the following stack-trace. Any help appreciated.

`E/AndroidRuntime(22801): java.lang.RuntimeException: Unable to start activity ComponentInfo{<redacted>/com.adapty.internal.crossplatform.ui.AdaptyUiActivity}: com.google.gson.JsonIOException: Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: com.adapty.models.AdaptyViewConfiguration$Asset
E/AndroidRuntime(22801): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3780)
E/AndroidRuntime(22801): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3942)
E/AndroidRuntime(22801): 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
E/AndroidRuntime(22801): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
E/AndroidRuntime(22801): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
E/AndroidRuntime(22801): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2345)
E/AndroidRuntime(22801): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(22801): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(22801): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(22801): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime(22801): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(22801): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(22801): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
E/AndroidRuntime(22801): Caused by: com.google.gson.JsonIOException: Abstract classes can't be instantiated! Register an InstanceCreator or a TypeAdapter for this type. Class name: com.adapty.models.AdaptyViewConfiguration$Asset
E/AndroidRuntime(22801): 	at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:136)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.createAccumulator(ReflectiveTypeAdapterFactory.java:425)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:381)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:186)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:144)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:431)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.readIntoField(ReflectiveTypeAdapterFactory.java:212)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$FieldReflectionAdapter.readField(ReflectiveTypeAdapterFactory.java:431)
E/AndroidRuntime(22801): 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:391)
E/AndroidRuntime(22801): 	at com.google.gson.Gson.fromJson(Gson.java:1214)
E/AndroidRuntime(22801): 	at com.google.gson.Gson.fromJson(Gson.java:1124)
E/AndroidRuntime(22801): 	at com.google.gson.Gson.fromJson(Gson.java:1034)
E/AndroidRuntime(22801): 	at com.google.gson.Gson.fromJson(Gson.java:969)
E/AndroidRuntime(22801): 	at com.adapty.internal.crossplatform.SerializationHelper.fromJson(SerializationHelper.kt:67)
E/AndroidRuntime(22801): 	at com.adapty.internal.crossplatform.CrossplatformHelper.fromJson(CrossplatformHelper.kt:33)
E/AndroidRuntime(22801): 	at com.adapty.internal.crossplatform.ui.PaywallUiManager.getPersistedData(PaywallUiManager.kt:86)
E/AndroidRuntime(22801): 	at com.adapty.internal.crossplatform.ui.PaywallUiManager.getData(PaywallUiManager.kt:18)
E/AndroidRuntime(22801): 	at com.adapty.internal.crossplatform.ui.PaywallUiManager.setCurrentView(PaywallUiManager.kt:68)
E/AndroidRuntime(22801): 	at com.adapty.internal.crossplatform.ui.AdaptyUiActivity.onCreate(AdaptyUiActivity.kt:39)
E/AndroidRuntime(22801): 	at android.app.Activity.performCreate(Activity.java:8129)
E/AndroidRuntime(22801): 	at android.app.Activity.performCreate(Activity.java:8109)
E/AndroidRuntime(22801): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1344)
E/AndroidRuntime(22801): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3749)
E/AndroidRuntime(22801): 	... 12 more`

**Comment by vladd-g** [comment]
hi @PetrKubes97, thank you! We will investigate the issue and get back to you soon.

**Comment by vladd-g** [comment]
hi @PetrKubes97, we've fixed it in v2.0.3 of the AdaptyUI library

**Comment by vladd-g** [comment]
@PetrKubes97 thank you for the logs, we'll investigate it

**Comment by vladd-g** [comment]
@PetrKubes97 could you please also provide the logs of the case when the close button is clicked on the first try?

**Comment by PetrKubes97** [comment]
There are no logs. I've also noticed that neither the Terms nor Privacy buttons work, whereas it's all running well on iOS (exact same build). So almost look like the AdaptyObserver is not getting triggered on Android.

**Comment by vladd-g** [comment]
Could you please check how it works on our sample app? But with your app's `applicationId` in `build.gradle` and your Adapty key. Just as it were your app, but with our sample's sources

**Comment by PetrKubes97** [comment]
The sample app works but I'm still getting the error and I'm unsure how to resolve it. I've removed the observer, so the code is literally just:
```
final view = await AdaptyUI().createPaywallView(paywall: paywall, locale: 'en');
view.present();
```
Looking in the logs by setting adapty logger to verbose, all of the network requests are successful, but the crash happens somewhere in the android code after `view.present();` is called. I'm not sure how to debug it.

I've also tried `flutter clean`, but that did not help.

**Comment by vladd-g** [comment]
Thank you!

> The sample app works but I'm still getting the error and I'm unsure how to resolve it. I've removed the observer

Am I correct that sample app has worked with no errors, and starting with "I'm still getting the error", including "I've removed the observer", it relates to the original app only?

**Comment by PetrKubes97** [comment]
Yes, the sample has worked with no errors.
